const video=document.getElementById("screen");let stream=null,busy=false;
const $=id=>document.getElementById(id);
function eventLog(s){const e=document.createElement("div");e.className="event";e.innerHTML=s;$("events").prepend(e);while($("events").children.length>12)$("events").lastChild.remove()}
async function analyse(){if(busy||!video.videoWidth)return;busy=true;$("status").textContent="● ANALYZING";try{const a=Vision.extractSeries(video);if(!a){$("decision").textContent="НЕТ ДАННЫХ";$("why").textContent="График не распознан. Увеличьте область графика.";return}const r=Indicators.rsi(a),m=Indicators.macd(a),lv=Indicators.levels(a),rv=r.filter(x=>x!=null).at(-1),mv=m.macd.at(-1),sv=m.signal.at(-1),hv=m.hist.at(-1),trend=a.at(-1)-a.at(-20),dir=trend>2&&mv>sv?"up":trend<-2&&mv<sv?"down":"flat",confidence=Math.min(96,Math.round(55+Math.abs(trend)*1.4+(dir!=="flat"?12:0))),risk=Math.max(8,Math.min(92,Math.round(100-confidence+(rv>70||rv<30?12:0)))),go=dir!=="flat"&&confidence>=65&&risk<48;
$("decision").textContent=go?(dir==="up"?"ВВЕРХ":"ВНИЗ"):"ЖДАТЬ";$("direction").textContent=dir==="up"?"↑ Положительная динамика":dir==="down"?"↓ Отрицательная динамика":"→ Боковое движение";$("direction").className=dir;$("why").textContent=go?"Есть подтверждение по тренду и MACD.":"Недостаточно подтверждений или риск слишком высок.";
$("confidence").textContent=confidence+"%";$("risk").textContent=risk+"%";$("strength").textContent=Math.min(99,Math.round(50+Math.abs(trend)*3))+"%";$("candles").textContent=a.length;$("price").textContent=a.at(-1).toFixed(2);$("trend").textContent=trend>=0?"Восходящий":"Нисходящий";$("support").textContent=lv.support.toFixed(2);$("resistance").textContent=lv.resistance.toFixed(2);
$("rsi").textContent=rv.toFixed(1);$("macd").textContent=mv.toFixed(3);$("macdSignal").textContent=(sv??0).toFixed(3);$("hist").textContent=(hv??0).toFixed(3);
if($("ocr").value==="on"){const o=await Vision.ocr(video);$("ocrPrice").textContent=o.price||"—";$("ocrText").textContent=o.text||"—"}eventLog("<b>"+$("decision").textContent+"</b> · "+$("horizon").value+"м · confidence "+confidence+"% · risk "+risk+"% · RSI "+rv.toFixed(1))}catch(e){eventLog("Ошибка анализа: "+e.message)}finally{busy=false;$("status").textContent="● LIVE"}}
$("start").onclick=async()=>{try{stream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:10,max:15}},audio:false});video.srcObject=stream;await video.play();$("status").textContent="● LIVE";stream.getVideoTracks()[0].onended=()=>{stream=null;$("status").textContent="● READY"}}catch(e){$("status").textContent="● READY"}};
$("stop").onclick=()=>{if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;$("status").textContent="● READY"};$("analyse").onclick=analyse;setInterval(()=>{if(stream)analyse()},2500);